// Regenerates lib/src/script_bundle.g.dart from ../../deploy/install/.
// Run from clients/dart_installer:  dart run tool/gen_bundle.dart
// test/bundle_test.dart fails when the generated file drifts from the sources.
import 'dart:convert';
import 'dart:io';

const files = {
  'install.sh': 'installSh',
  'docker-compose.yml.tpl': 'composeTpl',
  'Caddyfile.tpl': 'caddyfileTpl',
};

void main() {
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_bundle.dart from deploy/install/ - DO NOT EDIT.')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln();
  for (final e in files.entries) {
    final bytes = File('../../deploy/install/${e.key}').readAsBytesSync();
    final b64 = base64.encode(bytes);
    out.writeln('/// ${e.key} (base64).');
    out.writeln('const ${e.value}B64 =');
    for (var i = 0; i < b64.length; i += 76) {
      final end = i + 76 > b64.length ? b64.length : i + 76;
      out.write("    '${b64.substring(i, end)}'");
      out.writeln(end == b64.length ? ';' : '');
    }
    out.writeln();
  }
  File('lib/src/script_bundle.g.dart').writeAsStringSync(out.toString());
}
